# Generated by Django 4.0.7 on 2022-12-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_toppost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
